#!/bin/bash

if [ -x ~/.fehbg ]; then
    ~/.fehbg
    wallpaper=$(grep -oP "'\K[^']+" ~/.fehbg | sed 's/[[:space:]]*$//')
else
    wallpath=$HOME/Pix/Wallpaper
    wallpaper=$(find "$wallpath" -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' \) | shuf -n 1)
    feh --bg-fill "$wallpaper"
fi

wal -c
wal -i "$wallpaper"

xdotool key super+F5